spring:
  profiles:
      active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pc?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.sheen.pc.mapper

pc:
  version: 0.1-SNAPSHOT
  swagger:
    title: pc
    description : pc english
    contact: pc

logging:
  level:
    root: info
    org.mybatis: info
    org.springframework: info
    org.springframework.jdbc: info
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countsql



